In [6]:
import pandas as pd

pd.set_option('display.max_rows', None)  # Hiển thị tất cả hàng
pd.set_option('display.max_columns', None)  # Hiển thị tất cả cột
pd.set_option('display.max_colwidth', None)  # Hiển thị toàn bộ nội dung trong ô

from sitecustomize import ROOT

In [ ]:
df = pd.read_csv(ROOT + "/data/csv/homecredit_columns_description.csv")

In [ ]:
df["Table"] = df["Table"].replace("application_{train|test}.csv", "train_test")

In [ ]:
df

,MyUnknownColumn,Table,Row,Description,Special
0,1,train_test,SK_ID_CURR,ID of loan in our sample,NaN
1,2,train_test,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,train_test,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,train_test,CODE_GENDER,Gender of the client,NaN
4,7,train_test,FLAG_OWN_CAR,Flag if the client owns a car,NaN
...,...,...,...,...,...
214,217,installments_payments.csv,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN
215,218,installments_payments.csv,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application
216,219,installments_payments.csv,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application
217,220,installments_payments.csv,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN
218,221,installments_payments.csv,AMT_PAYMENT,What the client actually paid on previous cred...,NaN

In [ ]:
tmp = df[df["Table"] == "train_test"]

In [ ]:
tmp["Table"] = "test"

C:\Users\Admin\AppData\Local\Temp\ipykernel_12828\1039460742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["Table"] = "test"

In [ ]:
tmp

,MyUnknownColumn,Table,Row,Description,Special
0,1,test,SK_ID_CURR,ID of loan in our sample,NaN
1,2,test,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,test,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,test,CODE_GENDER,Gender of the client,NaN
4,7,test,FLAG_OWN_CAR,Flag if the client owns a car,NaN
...,...,...,...,...,...
117,120,test,AMT_REQ_CREDIT_BUREAU_DAY,Number of enquiries to Credit Bureau about the...,NaN
118,121,test,AMT_REQ_CREDIT_BUREAU_WEEK,Number of enquiries to Credit Bureau about the...,NaN
119,122,test,AMT_REQ_CREDIT_BUREAU_MON,Number of enquiries to Credit Bureau about the...,NaN
120,123,test,AMT_REQ_CREDIT_BUREAU_QRT,Number of enquiries to Credit Bureau about the...,NaN
121,124,test,AMT_REQ_CREDIT_BUREAU_YEAR,Number of enquiries to Credit Bureau about the...,NaN

In [ ]:
tmp = tmp[tmp["Row"] != "TARGET"]

In [ ]:
df = pd.concat([df, tmp])

In [ ]:
df = df.replace("train_test", "train")

In [ ]:
df["Table"] = df["Table"].str.replace(r".csv$", "", regex=True)

In [ ]:
df

,MyUnknownColumn,Table,Row,Description,Special
0,1,train,SK_ID_CURR,ID of loan in our sample,NaN
1,2,train,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,train,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,train,CODE_GENDER,Gender of the client,NaN
4,7,train,FLAG_OWN_CAR,Flag if the client owns a car,NaN
...,...,...,...,...,...
117,120,test,AMT_REQ_CREDIT_BUREAU_DAY,Number of enquiries to Credit Bureau about the...,NaN
118,121,test,AMT_REQ_CREDIT_BUREAU_WEEK,Number of enquiries to Credit Bureau about the...,NaN
119,122,test,AMT_REQ_CREDIT_BUREAU_MON,Number of enquiries to Credit Bureau about the...,NaN
120,123,test,AMT_REQ_CREDIT_BUREAU_QRT,Number of enquiries to Credit Bureau about the...,NaN
121,124,test,AMT_REQ_CREDIT_BUREAU_YEAR,Number of enquiries to Credit Bureau about the...,NaN

In [ ]:
df.to_csv(ROOT + "/data/csv/description.csv", index=False)
df.to_pickle(ROOT + "/data/pkl/description.p")